### ISSUE TITLE
Info box doesn't scroll on mobile

### ISSUE THREAD

**Issue by mrand** [Judo-Documentation-Project/budotree#24]
Or at least on my mobile (Chrome).

**Comment by fsmunoz** [comment]
Thank you for reporting this. I can confirm the behaviour on Chrome and Safari (iOS), although it works as expected using Chrome DevTools emulation. Problem is likely on the Bulma component used (Card), will take a look.

**Comment by fsmunoz** [comment]
@mrand could you give it a try?

**Comment by mrand** [comment]
Looks good now!

**Comment by fsmunoz** [comment]
For future reference, this is apparently due to how mobile browsers deal with scrolling with `position: absolute` divs. Many different suggestions exist around `overflow*` options and `-webkit-overflow-scrolling: touch;` (which looks deprecated). The solution was achieved through trial and error since the behaviour is not present in dev simulators, only in the physical devices.
