### ISSUE TITLE
Proper way to address multiple arts between a student and teacher

### ISSUE THREAD

**Issue by mrand** [Judo-Documentation-Project/budotree#35]
Not obvious to me the correct way to do this.  Miyake Tsunako and Tomiki are an obvious example (both judo and aikido), but I'm sure there are endless others.

- Can you just list multiple style_id's under someones teacher?
- Or should the teacher be listed twice, once for each style_id?
- Will this create two arrow links in the graphical presentation, or will it use one arrow and list two arts?

**Comment by fsmunoz** [comment]
Hello,

Great topic, thank you for bringing this up - I have been evading this not on purpose, but out of the way I've been directing the research more based on following the "styles" than harvesting everything about a single person.

There are two aspects to this topic, which are separate:

1. **The database format**: this is, for me, what takes precedence: to accommodate something reasonable (like what your're describing), the format should do what's simpler and logical (or at least, the closest to it).
2. **The web UI**: this should adapt itself to the format, when needed, especially because the web UI here is one of other possible tools that rely on the format. The web tree, although the "sexier" part of the project, should not dictate the format (except in cases where all things are equal), but adapt to it.

Starting with the database, I think that adding two `id: ` entries is the simplest and aligned with the overarching goal:

* There are entries (place, period) which are related with that specific relation, so unless we would change them to be under `style_id`, they would not be changeable per art.
* The `teachers` entry represents a "transmission line" which is tied to the teacher/style combination, which is why the arrow line has the name of the style.

I can, however,  see an argument about how the teacher could be the a sort of unique key there, and styles listed under it... this would move things under a `style_id`. I will note that even in genealogy (which represents more lasting relations, in general), the link between individual and family is a single link, but this shouldn't concern us: here we are focusing on the (sometimes fleeting) links between persons, with a big emphasis on _what_ they taught. 

Happy yo continue this discussion though, and if needed the format can be changed (and the parsing adapted).

In terms of the UI (again, this is a different matter since one thing is what will happen by default, another is what we think is better - things can be processed in a way that both work regardless of the database format) it will create two links, which I think is the right thing to do - especially when considering that when you filter things, some of them disappear.

I made a quick experiment in a local branch to see how it would work, and it seems that Cytoscape does "the right thing": the links do not overlap (that would be my main concern)

![image](https://github.com/Judo-Documentation-Project/budotree/assets/285727/decbddbe-7c26-4d62-b444-3b59a23170c7)

What does happen is that the "extra" links are visible even when filtering by style:

![image](https://github.com/Judo-Documentation-Project/budotree/assets/285727/6141e1ed-84ce-4818-aa32-09b42c244206)

This is easily fixed though - assuming we want to have the behaviour. What do you think?

**Comment by mrand** [comment]
1. While it's more verbose, multiple `id:` entries makes sense to me since it keeps the quality, dates, and sources distinct for each art.
2. I think it probably makes sense to only display the filtered art, at least by default.  I tend to like options, as long as there aren't an overwhelming number - so if it can be done easily without making the UI complicated, maybe a switch somewhere which allows for "showing all arts between people, regardless of filter" in a 'Settings' pull-down or pop-up?
3. I'm afraid it would ruin the clean look of the tree - BUT there are certain situations where I'd like to see it. Where I think it might be especially interesting is easily comparing when various students studied from the same teacher - who overlapped and/or who came to them much later.  So maybe similar solution to (2) above.

**Comment by fsmunoz** [comment]
Thanks @mrand . I will add update the documentation to reflect this way of doing things, and I will also explore how to add those other two as options - it's trivial from a programmatic perspective , I'm more concerned with the UI (even the current one should be analysed in terms of usability).

**Comment by fsmunoz** [comment]
@mrand I'm going to open a different issue for the 3rd topic on label lines. In terms of the filtering, I left it out since the idea of filtering by style is to only see those lines, I don't think it's important that the teacher is the same or not - that can be viewed in different ways, and I think it is more related with some additional filtering options that should be a separate issue as well, even because each time an UI element is added it can make things worse.

**Comment by mrand** [comment]
I think it works well as is currently: if a user doesn't filter by art, then it shows the double links.  If they do filter, it only shows one link.
